// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PousadaApi.Infrastructure.Data.Context;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(PousadaDbContext))]
    [Migration("20260519200831_AddCalendarioExternoAndReservaMultiCanal")]
    partial class AddCalendarioExternoAndReservaMultiCanal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PousadaApi.Domain.Entities.CalendarioExterno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("QuartoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimaSincronizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("UrlImportacao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("QuartoId");

                    b.ToTable("CalendariosExternos");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.Hospede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PousadaId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PousadaId");

                    b.ToTable("Hospedes");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.Pousada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pousadas");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.Quarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroOuNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PousadaId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TokenExportacao")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PousadaId");

                    b.HasIndex("TokenExportacao")
                        .IsUnique();

                    b.ToTable("Quartos");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalendarioExternoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HospedeId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("QuartoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SincronizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TituloExterno")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UidExterno")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CalendarioExternoId");

                    b.HasIndex("HospedeId");

                    b.HasIndex("DataEntrada", "DataSaida");

                    b.HasIndex("QuartoId", "UidExterno")
                        .IsUnique()
                        .HasFilter("\"UidExterno\" IS NOT NULL");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.CalendarioExterno", b =>
                {
                    b.HasOne("PousadaApi.Domain.Entities.Quarto", "Quarto")
                        .WithMany("CalendariosExternos")
                        .HasForeignKey("QuartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quarto");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.Hospede", b =>
                {
                    b.HasOne("PousadaApi.Domain.Entities.Pousada", "Pousada")
                        .WithMany("Hospedes")
                        .HasForeignKey("PousadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pousada");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.Pousada", b =>
                {
                    b.HasOne("PousadaApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Pousadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.Quarto", b =>
                {
                    b.HasOne("PousadaApi.Domain.Entities.Pousada", "Pousada")
                        .WithMany("Quartos")
                        .HasForeignKey("PousadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pousada");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("PousadaApi.Domain.Entities.CalendarioExterno", "CalendarioExterno")
                        .WithMany("Reservas")
                        .HasForeignKey("CalendarioExternoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PousadaApi.Domain.Entities.Hospede", "Hospede")
                        .WithMany("Reservas")
                        .HasForeignKey("HospedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PousadaApi.Domain.Entities.Quarto", "Quarto")
                        .WithMany("Reservas")
                        .HasForeignKey("QuartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarioExterno");

                    b.Navigation("Hospede");

                    b.Navigation("Quarto");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.CalendarioExterno", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.Hospede", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.Pousada", b =>
                {
                    b.Navigation("Hospedes");

                    b.Navigation("Quartos");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.Quarto", b =>
                {
                    b.Navigation("CalendariosExternos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("PousadaApi.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Pousadas");
                });
#pragma warning restore 612, 618
        }
    }
}
